---
driver:
  name: docker
  hostname: opencontrail
  use_sudo: true

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: opencontrail
  grains:
    noservices: True
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux
  state_top:
    base:
      "*":
        - linux
        - opencontrail
  pillars:
    top.sls:
      base:
        "*":
          - linux_repo_openstack
          - linux_repo_opencontrail
          - linux_repo_cassandra
          - linux
          - opencontrail
          - opencontrail_juniper
    linux.sls:
      linux:
        system:
          enabled: true
          name: opencontrail
    opencontrail_juniper.sls: {}
  pillars-from-files:
    linux_repo_cassandra.sls: tests/pillar/repo_cassandra.sls
    linux_repo_opencontrail.sls: tests/pillar/repo_opencontrail_<%= ENV['OC_REPO'] || 'oc311' %>.sls
    linux_repo_openstack.sls: tests/pillar/repo_openstack.sls

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%= ENV['PLATFORM'] || 'ubuntu-xenial' %>
    driver_config:
      image: <%= ENV['PLATFORM'] || 'trevorj/salty-whales:xenial' %>
      platform: ubuntu

suites:

  # - name: single<%= ENV['OC_VERSION'] || '' %>
  #   provisioner:
  #     pillars-from-files:
  #       opencontrail.sls: tests/pillar/single<%= ENV['OC_VERSION'] || '' %>.sls
  - name: analytics<%= ENV['OC_VERSION'] || '' %>
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/analytics<%= ENV['OC_VERSION'] || '' %>.sls
  - name: control<%= ENV['OC_VERSION'] || '' %>
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/control<%= ENV['OC_VERSION'] || '' %>.sls
  # - name: cluster<%= ENV['OC_VERSION'] || '' %>
  #   provisioner:
  #     pillars-from-files:
  #       opencontrail.sls: tests/pillar/cluster<%= ENV['OC_VERSION'] || '' %>.sls
  - name: tor<%= ENV['OC_VERSION'] || '' %>
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/tor<%= ENV['OC_VERSION'] || '' %>.sls
  - name: vrouter<%= ENV['OC_VERSION'] || '' %>
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/vrouter<%= ENV['OC_VERSION'] || '' %>.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
